### ISSUE TITLE
Over-crowded footer

### ISSUE THREAD

**Issue by pleia2** [knomepasi/ubuntu-community-wordpress-theme#8] opened 2016-02-08 01:06 UTC
For ubuntu-us.org we're pretty conservative and specific about the links we're making available on the site, particularly when it comes to blog-specific links and Meta links. This theme makes them all available in what ends up being a very crowded footer for an active site. Our live site doesn't really have any of these links, and we like it that way :)

![ubuntu-us-test-knome-theme-2](https://cloud.githubusercontent.com/assets/879924/12876836/27d751a6-cdbd-11e5-8b47-60d9f9f3591b.png)

**Comment by knomepasi** [comment] 2016-02-08 01:14
This is essentially duplicate of part of #6.

The widgets appear here because WordPress thinks you want to have them set up. Simply remove the widgets from the Footnote widget area and they will be gone. When you have no widgets in that area, it will vanish from the theme.

**Closed as completed by knomepasi** 2016-02-08 01:14 UTC
Labels: question
